=== cziko1/O2IXLB_XMLgyak/O2IXLB_09_28/CzT_konyv.dtd
<!ELEMENT konyvek (konyv+)>
<!ELEMENT konyv (cim,ev,kiado,szerzo,absztrakt)>
<!ATTLIST konyv id NMTOKEN #REQUIRED>
<!ELEMENT cim (#PCDATA)>
<!ELEMENT ev (#PCDATA)>
<!ELEMENT kiado (#PCDATA)>
<!ELEMENT szerzo (#PCDATA)>
<!ELEMENT absztrakt (#PCDATA|absztrakt)*>

=== cziko1/O2IXLB_XMLgyak/O2IXLB_09_28/CzT_konyvek.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE CzT_konyv SYSTEM "CzT_konyv.dtd">

<konyvek>
	<konyv id="BP1">
		<cim>Programozas Alapjai</cim>
		<ev>2020</ev>
		<kiado>Oxford kiado</kiado>
		<szerzo>Szerzo Bela</szerzo>
		<absztrakt>qwetyQWERTY12345_ZUIOP-ikjli</absztrakt>
	</konyv>

	<konyv id="BP2">
		<cim>Objektum Orientalt Programozas</cim>
		<ev>2021</ev>
		<kiado>Bookworms</kiado>
		<szerzo>Iro July</szerzo>
		<absztrakt> neofnwoefnho-hsdbguzrbvsrdrger</absztrakt>
	</konyv>

	<konyv id="BP3">
		<cim>How to use PyCharm</cim>
		<ev>2022</ev>
		<kiado>Programing kiado</kiado>
		<szerzo>Programozo Szabi</szerzo>
		<absztrakt>nevi-uwehsnkc.alkerpiqohrandmer<absztrakt>
	</konyv>
</konyvek>
