=== cziko1/O2IXLB_XMLgyak/O2IXLB_09_28/CzT_ertodtd.dtd
<!ELEMENT task (A,A_B,B,C)>
<!ELEMENT A (Ab,Ac)>
<!ATTLIST A Aa NMTOKEN #REQUIRED>
<!ELEMENT Ab (Abx,Aby)>
<!ELEMENT Abx EMPTY>
<!ELEMENT Aby EMPTY>
<!ELEMENT Ac (Acd,Ace)>
<!ELEMENT Acd EMPTY>
<!ELEMENT Ace EMPTY>
<!ELEMENT A_B (A_Bc)>
<!ELEMENT A_Bc EMPTY>
<!ELEMENT B (Bb)>
<!ATTLIST B Ba NMTOKEN #REQUIRED>
<!ELEMENT Bb (Bbx,Bby)>
<!ELEMENT Bbx EMPTY>
<!ELEMENT Bby EMPTY>
<!ELEMENT C (Cb)>
<!ATTLIST C Ca NMTOKEN #REQUIRED>
<!ELEMENT Cb EMPTY>

=== cziko1/O2IXLB_XMLgyak/O2IXLB_09_28/CzT_ertoxml.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE task SYSTEM "CzT_ertodtd.dtd">
<task>
    <A Aa="101">
        <Ab>
            <Abx></Abx>
            <Aby></Aby>
        </Ab>
        <Ac>
            <Acd></Acd>
            <Ace></Ace>
        </Ac>
    </A>
    <A_B>
        <A_Bc></A_Bc>
    </A_B>
    <B Ba="202">
        <Bb>
            <Bbx></Bbx>
            <Bby></Bby>
        </Bb>
    </B>
    <C Ca="303">
        <Cb></Cb>
    </C>
</task>
